# usage: ansible-playbook example-playbook.yml --extra-vars=""
---
- name: install uwsgi
  hosts: vagrant
  sudo: True
  user: vagrant
  gather_facts: False
  vars:
    version: 1.2.3+dfsg-5
  tasks:
    - include: roles/uwsgi/tasks/main.yml
  handlers:
    - include: roles/uwsgi/handlers/main.yml
