---
  - name: fail2ban | fail2ban_os_ubuntu.yml >> fail2ban present
    apt: pkg={{ fail2ban.package }}={{ fail2ban.version }} state=present
    environment: "{{ env }}"

  - name: fail2ban | fail2ban_os_ubuntu.yml >> fail2ban conf present
    template: src={{ item.src_path }} dest={{ item.target_path }} mode=0644 owner=root group=root
    with_items:
      - { src_path: "{{ fail2ban.conf.src_path }}", target_path: '/etc/fail2ban/jail.local' }
    notify:
      - restart fail2ban
