---
  - name: lynis | main.yml >> latest lynis present
    apt: pkg=lynis state=latest
    environment: env.proxies
    tags: lynis

  - name: lynis | main.yml >> lynis daily cron present
    template: src=lynis.cron.j2
              dest=/etc/cron.daily/lynis
              owner=root
              group=root
              mode=0755
    tags: lynis
