---
  - name: common | security.yml >> fail2ban installed
    apt: pkg=fail2ban state=present

  - name: common | security.yml >> chkrootkit installed
    apt: pkg=chkrootkit state=present

  - name: common | security.yml >> rkhunter installed
    apt: pkg=rkhunter state=present

  - name: common | security.yml >> tiger installed
    apt: pkg=tiger state=present

  - name: common | security.yml >> prevent ip spoof
    lineinfile: dest=/etc/host.conf regexp="^order" line="order bind,hosts" state=present

  - name: common | security.yml >> prevent ip spoof
    lineinfile: dest=/etc/host.conf regexp="^nospoof" line="nospoof on" state=present
