---
  - name: hostname | main.yml >> set hostname in /etc/hostname
    copy: content={{ hostname }} dest=/etc/hostname
    when: hostname is defined and hostname
    tags: hostname

  - name: hostname | main.yml >> configure hostname in /etc/hosts
    lineinfile: dest=/etc/hosts regexp="^127.0.1.1" line="127.0.1.1 {{ hostname }}"
    when: hostname is defined and hostname
    register: hostname_configured
    tags: hostname

  - name: hostname | main.yml >> set hostname
    command: /bin/hostname -F /etc/hostname
    when: hostname is defined and hostname and hostname_configured.changed
    tags: hostname
