---
  - name: logrotate | main.yml >> logrotate present
    apt: pkg={{ logrotate.package }}={{ logrotate.version }} state=present
    environment: env.proxies
    tags: logrotate

  - name: logrotate | main.yml >> logrotate conf present
    template: src={{ item.src }} dest={{ item.dest }} mode=0644 owner=root group=root
    with_items:
      - { src: 'logrotate.conf.j2', dest: '/etc/logrotate.conf' }
    tags: logrotate
