# usage: ansible-playbook example-playbook.yml --extra-vars=""
---
- name: install nginx
  hosts: vagrant
  sudo: True
  user: vagrant
  gather_facts: False
  vars:
    version: 1.2.1-2.2
    worker_processes: 1
    worker_connections: 1
    pid: /var/run/nginx.pid
    user: vagrant
  tasks:
    - include: roles/nginx/tasks/main.yml
  handlers:
    - include: roles/nginx/handlers/main.yml
