---
  - name: elasticsearch | main.yml >> create elasticsearch group
    group: name={{ elasticsearch.group }} state=present system=yes

  - name: elasticsearch | main.yml >> create elasticsearch user
    user: name={{ elasticsearch.user }} group={{ elasticsearch.group }} createhome=no shell=/bin/false system=yes state=present

  - name: elasticsearch | main.yml >> download elasticsearch
    get_url: url={{ elasticsearch.download_url }}/{{ elasticsearch.package }} dest={{ elasticsearch.staging_dir }}/{{ elasticsearch.package }} thirsty=no mode=0644
    register: elasticsearch_downloaded
    tags: elasticsearch

  - name: elasticsearch | main.yml >> install elasticsearch
    shell: "dpkg -i {{ elasticsearch.staging_dir}}/{{ elasticsearch.package }} 2>&1"
    when: elasticsearch_downloaded.changed
    tags: elasticsearch

  - name: elasticsearch | main.yml >> install elasticsearch config
    template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml group={{ elasticsearch.group }} owner={{ elasticsearch.user }} mode=0644
    tags: elasticsearch
    notify: restart elasticsearch

  - name: elasticsearch | main.yml >> install elasticsearch logging config
    template: src=logging.yml.j2 dest=/etc/elasticsearch/logging.yml group={{ elasticsearch.group }} owner={{ elasticsearch.user }} mode=0644
    tags: elasticsearch
    notify: restart elasticsearch
