---
  - name: rvm | main.yml >> curl present
    apt: pkg=curl state=latest
    environment: env.proxies
    tags: rvm

  - name: rvm | main.yml >> rvm present
    shell: /usr/bin/curl -L https://get.rvm.io | bash -s stable creates=/usr/local/rvm/bin/rvm
    tags: rvm
