---
  - name: javaenv | main.yml >> jre present
    apt: pkg={{ java.jre.package }}={{ java.jre.version }} state=present
    environment: env.proxies
    when: java.jre is defined and java.jre
    tags: javaenv, javaenv-jre
