---
  - name: haproxy | main.yml >> haproxy present
    apt: pkg={{ haproxy.package }}={{ haproxy.version }} state=present
    environment: env.proxies
    tags: haproxy

  - name: haproxy | main.yml >> create haproxy group
    group: name={{ haproxy.group }} state=present system=yes
    when: haproxy.group is defined and haproxy.group
    tags: haproxy

  - name: haproxy | main.yml >> create haproxy user
    user: name={{ haproxy.user }} group={{ haproxy.group }} createhome=no shell=/bin/false system=yes state=present
    when: haproxy.user is defined and haproxy.user
    tags: haproxy

  - name: haproxy | main.yml >> haproxy logrotate conf present
    template: src=haproxy.logrotate.j2 dest=/etc/logrotate.d/haproxy mode=0644
    tags: haproxy

  - name: haproxy | main.yml >> enable haproxy
    lineinfile: dest=/etc/default/haproxy regexp=^ENABLED=.$ line=ENABLED=1
    notify:
      - restart haproxy
    tags: haproxy

  - name: haproxy | main.yml >> haproxy conf present
    template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0644 owner=root group=root
    notify:
      - restart haproxy
    tags: haproxy
