---
  - name: sshd | sshd_os_ubuntu.yml >> sshd present
    apt: pkg={{ sshd.package }}={{ sshd.version }} state=present
    environment: env

  - name: sshd | sshd_os_ubuntu.yml >> sshd conf present
    template: src={{ sshd.config.src }} dest=/etc/ssh/sshd_config mode=0640 owner=root group=root backup=yes
    notify:
      - restart sshd
