---
  - name: ntp | main.yml >> latest ntp present
    apt: pkg=ntp state=latest
    environment: env.proxies
    tags: ntp

  - name: ntp | main.yml >> ntp conf present
    template: src=ntp.conf.j2 dest=/etc/ntp.conf mode=0640 owner=root group=root
    notify:
      - restart ntp
    tags: ntp
