---
  - name: memcached | main.yml >> memcached present
    apt: pkg={{ item }}={{ memcached.version }} state=present
    with_items:
      - memcached
    tags: memcached, install
    register: memcached_present

  - debug: msg="installed memcached {{ memcached.version }}"
    when: memcached_present.changed

  - name: memcached | main.yml >> create memcached group
    group: name={{ memcached.group }} state=present system=yes

  - name: memcached | main.yml >> create memcached user
    user: name={{ memcached.user }} group={{ memcached.group }} createhome=no shell=/bin/false system=yes state=present

  - name: memcached | main.yml >> install memcached config
    template: src=memcached.conf.j2 dest=/etc/memcached.conf group={{ memcached.group }} owner={{ memcached.user }}
    notify:
      - restart memcached
    tags: memcached
